version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building application..."
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
